//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SystemExplorer.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SEARCHBAR                   103
#define IDD_PROCESS_PROPERTIES          107
#define IDR_MAINFRAME                   128
#define IDS_TITLE                       129
#define IDR_DRIVER                      202
#define IDI_JOB                         203
#define IDI_DESKTOP                     204
#define IDI_DEVICE                      205
#define IDI_DIRECTORY                   206
#define IDI_EVENT                       207
#define IDI_FILE                        208
#define IDI_GENERIC                     209
#define IDI_KEY                         210
#define IDI_MUTEX                       211
#define IDI_PORT                        212
#define IDI_PROCESS                     213
#define IDI_SECTION                     214
#define IDI_SEMAPHORE                   215
#define IDI_SYMLINK                     216
#define IDI_THREAD                      217
#define IDI_TIMER                       218
#define IDI_TOKEN                       219
#define IDI_PAUSE                       220
#define IDI_WINSTATION                  221
#define IDI_OBJECTS                     222
#define IDI_TYPES                       223
#define IDD_PROCSELECT                  224
#define IDR_CONTEXT                     227
#define IDD_HANDLES                     228
#define IDI_COPY                        230
#define IDI_REFRESH                     231
#define IDI_HANDLES                     232
#define IDI_PROCESS_VIEW                233
#define IDI_DELETE                      234
#define IDI_ABOUT                       236
#define IDI_PACKAGE                     237
#define IDI_PIN                         238
#define IDI_FOLDER                      239
#define IDI_FOLDER_CLOSED               240
#define IDI_ATOM                        243
#define IDI_BATTERY                     244
#define IDI_CAR                         245
#define IDI_DRAM                        246
#define IDI_FILTER                      247
#define IDI_FILTER_UP                   248
#define IDI_WINDOW                      249
#define IDI_WINDOWS                     250
#define IDI_NOACCESS                    251
#define IDI_WINDOW_BLACK                252
#define IDI_WINDOW_TITLE                253
#define IDI_FACTORY                     254
#define IDI_FIND                        255
#define IDI_BRUSH                       256
#define IDI_FIND_NEXT                   257
#define IDI_WINDOW_CLOSE                258
#define IDI_SERVICE                     259
#define IDI_SERVICE_DELETE              260
#define IDI_SERVICE_PAUSE               261
#define IDI_SERVICE_RUNNING             262
#define IDI_SERVICE_STOP                263
#define IDI_SERVICES                    264
#define IDI_PLAY                        265
#define IDI_STOP                        266
#define IDD_PROGRESS                    267
#define IDI_RESUME                      270
#define IDD_SERVICE_INSTALLER           271
#define IDI_OK                          275
#define IDD_PIPES_MAILSLOTS             276
#define IDI_MAILBOX                     278
#define IDI_PIPE                        279
#define IDI_WINDOW_NEW                  280
#define IDI_COMMIT                      281
#define IDI_FREE                        282
#define IDI_RESERVED                    283
#define IDI_FONT                        284
#define IDI_SHIELD2                     285
#define IDI_LOGIN                       286
#define IDD_COLUMNS                     287
#define IDI_HIDECOLUMN                  289
#define IDI_EDITCOLUMNS                 290
#define IDI_DLL                         291
#define IDI_DLL_DB                      292
#define IDI_DLL_RELOC                   293
#define IDI_HEAP                        294
#define IDI_PROCESSES                   296
#define IDI_COMPONENT                   297
#define IDI_INIT                        298
#define IDI_READY                       299
#define IDI_RUNNING                     300
#define IDI_STANDBY                     301
#define IDI_TRANSITION                  302
#define IDI_APPID                       304
#define IDI_CLASS                       305
#define IDI_INTERFACE                   306
#define IDI_LIBRARY                     307
#define IDI_APP_SERVER                  308
#define IDI_DLL_SERVER                  309
#define IDI_RUN                         313
#define IDI_VARS                        314
#define IDI_FOLDER_FIND                 315
#define IDD_TOKEN                       316
#define IDC_PROCLIST                    1000
#define IDC_HANDLES                     1000
#define IDC_GITHUB                      1001
#define IDC_NAME                        1002
#define IDC_COUNT                       1003
#define IDC_PATH                        1003
#define IDC_PID                         1004
#define IDC_PROGRESS                    1005
#define IDC_COMMANDLINE                 1005
#define IDC_MESSAGE                     1006
#define IDC_CURDIR                      1007
#define IDC_EDIT2                       1008
#define IDC_DISPLAYNAME                 1008
#define IDC_PRIORITY                    1008
#define IDC_REFRESH                     1009
#define IDC_DESC                        1009
#define IDC_SERVICETYPE                 1010
#define IDC_STARTTYPE                   1011
#define IDC_LIST                        1011
#define IDC_COLUMNS                     1012
#define IDC_ERROR_CONTROL               1012
#define IDC_TREE                        1013
#define IDC_TYPE                        1014
#define IDC_TYPE2                       1015
#define IDC_TEXT                        1016
#define IDC_SEARCH                      1017
#define IDC_BUTTON2                     1018
#define IDC_CANCEL                      1018
#define IDC_ENV                         1018
#define IDC_EXPLORE                     1020
#define IDC_TOKEN                       1021
#define IDC_JOB                         1022
#define IDC_APPICON                     1023
#define IDC_COPY                        1024
#define IDC_PARENT                      1025
#define IDC_USERNAME                    1026
#define IDC_USERSID                     1027
#define IDC_DOTNET                      1027
#define IDC_PRICLASS                    1028
#define IDC_STATS                       1028
#define IDC_PLATFORM                    1029
#define IDC_CREATED                     1030
#define IDC_EXPLORE_DIR                 1031
#define IDC_GROUPS                      1032
#define IDC_PRIVILEGES                  1033
#define IDC_SESSION                     1034
#define IDC_INTEGRITY                   1035
#define IDC_VIRT                        1036
#define IDC_LOGONSESSION                1037
#define IDC_ELEVATED                    1038
#define IDC_GROUP_COUNT                 1039
#define ID_WINDOW_CLOSE                 32772
#define ID_WINDOW_CLOSE_ALL             32773
#define ID_SEARCH_FIND                  32775
#define ID_OBJECTS_SHOWOBJECTSOFTYPE    32776
#define ID_SHOWOBJECTSOFTYPE_PROCESS    32777
#define ID_SHOWOBJECTSOFTYPE_THREAD     32778
#define ID_SHOWOBJECTSOFTYPE_JOB        32779
#define ID_SHOWOBJECTSOFTYPE_EVENT      32780
#define ID_SHOWOBJECTSOFTYPE_MUTEX      32781
#define ID_SHOWOBJECTSOFTYPE_SEMAPHORE  32782
#define ID_SHOWOBJECTSOFTYPE_TOKEN      32783
#define ID_SHOWOBJECTSOFTYPE_FILE       32784
#define ID_SHOWOBJECTSOFTYPE_SYMBOLICLINK 32785
#define ID_SHOWOBJECTSOFTYPE_ALPCPORT   32786
#define ID_SHOWOBJECTSOFTYPE_TIMER      32787
#define ID_SHOWOBJECTSOFTYPE_DESKTOP    32788
#define ID_SHOWOBJECTSOFTYPE_WINDOWSTATION 32789
#define ID_SHOWOBJECTSOFTYPE_KEY        32790
#define ID_SHOWOBJECTSOFTYPE_DIRECTORY  32791
#define ID_SHOWOBJECTSOFTYPE_SECTION    32792
#define ID_SHOWOBJECTSOFTYPE_POWERREQUEST 32793
#define ID_SHOWOBJECTSOFTYPE_WORKERFACTORY 32794
#define ID_OBJECTS_ALLOBJECTS           32800
#define ID_VIEW_PAUSE                   32801
#define ID_OBJECTS_OBJECTMANAGER        32802
#define ID_OBJECTS_ALLOBJECTTYPES       32803
#define ID_HANDLES_ALLHANDLES           32804
#define ID_HANDLES_SHOWHANDLESOFTYPE    32805
#define ID_SHOWHANDLESOFTYPE_PROCESS    32805
#define ID_SHOWHANDLESOFTYPE_THREAD     32806
#define ID_SHOWHANDLESOFTYPE_JOB        32807
#define ID_SHOWHANDLESOFTYPE_EVENT      32808
#define ID_SHOWHANDLESOFTYPE_MUTEX      32809
#define ID_SHOWHANDLESOFTYPE_SEMAPHORE  32810
#define ID_SHOWHANDLESOFTYPE_TOKEN      32811
#define ID_SHOWHANDLESOFTYPE_FILE       32812
#define ID_SHOWHANDLESOFTYPE_SYMBOLICLINK 32813
#define ID_SHOWHANDLESOFTYPE_ALPCPORT   32814
#define ID_SHOWHANDLESOFTYPE_TIMER      32815
#define ID_SHOWHANDLESOFTYPE_DESKTOP    32816
#define ID_SHOWHANDLESOFTYPE_WINDOWSTATION 32817
#define ID_SHOWHANDLESOFTYPE_KEY        32818
#define ID_SHOWHANDLESOFTYPE_DIRECTORY  32819
#define ID_SHOWHANDLESOFTYPE_SECTION    32820
#define ID_SHOWHANDLESOFTYPE_POWERREQUEST 32821
#define ID_SHOWHANDLESOFTYPE_WORKERFACTORY 32822
#define ID_HANDLES_SHOWHANDLEINPROCESS  32823
#define ID_HANDLES_PIPES                32824
#define ID_HANDLES_CLOSEHANDLE          32825
#define ID_OBJECTS_DRIVERS              32826
#define ID_WINDOW_CLOSEALLBUTTHIS       32827
#define ID_OBJECTS_ALLHANDLESFOROBJECT  32828
#define ID_OPTIONS_ALWAYSONTOP          32829
#define ID_OBJECT                       32831
#define ID_TYPE_ALLOBJECTS              32832
#define ID_TYPE_ALLHANDLES              32833
#define ID_DESKTOPS_ALLWINDOWS          32837
#define ID_GUI_WINDOWSINPROCESS         32838
#define ID_GUI_GDIOBJECTSINPROCESS      32839
#define ID_GUI_ALLWINDOWSINDEFAULTDESKTOP 32840
#define ID_SYSTEM_SERVICES              32841
#define ID_SYSTEM_DEVICES               32842
#define ID_SYSTEM_DRIVERS               32843
#define ID_SERVICE_START                32844
#define ID_SERVICE_STOP                 32845
#define ID_SERVICE_PAUSE                32846
#define ID_SERVICE_CONTINUE             32847
#define ID_SERVICE_UNINSTALL            32848
#define ID_FILE_RUNASADMINISTRATOR      32849
#define ID_SYSTEM_COM                   32850
#define ID_SYSTEM_INSTALLSERVICE        32851
#define ID_OBJECTS_MAILSLOTS            32852
#define ID_TAB_DETACH                   32853
#define ID_SYSTEM_PROCESSES             32854
#define ID_SYSTEM_THREADS               32855
#define ID_PROCESS_MEMORYMAP            32856
#define ID_PROCESS_THREADS              32857
#define ID_PROCESS_MODULES              32858
#define ID_PROCESS_HEAPS                32859
#define ID_TAB_NEWWINDOW                32860
#define ID_HEADER_HIDECOLUMN            32861
#define ID_HEADER_COLUMNS               32862
#define ID_HANDLES_NAMEDOBJECTSONLY     32863
#define ID_EDIT_SECURITY                32864
#define ID_SYSTEM_LOGONSESSIONS         32865
#define ID_PROCESS_KILL                 32866
#define ID_PROCESS_PRIORITYCLASS        32867
#define ID_PRIORITYCLASS_IDLE           32868
#define ID_PRIORITYCLASS_BELOWNORMAL    32869
#define ID_PRIORITYCLASS_NORMAL         32870
#define ID_PRIORITYCLASS_ABOVENORMAL    32871
#define ID_PRIORITYCLASS_HIGH           32872
#define ID_PRIORITYCLASS_REALTIME       32873
#define ID_PROCESS_GOTOFILELOCATION     32874
#define ID_TAB_DETACH32875              32875
#define ID_FILE_EXITALL                 32876
#define ID_PROCESS_ALLOFTHEABOVE        32877
#define ID_SYSTEM_SEARCH                32878
#define ID_EDIT_PROPERTIES              32879

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32882
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
